baseURL = 'https://robinvenables.com/'
languageCode = 'en-gb'
title = 'Robin Venables'
theme = "mainroad"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[Params]
  description = "An IT consultant at work and play"
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "categories", "tags"] # Order of post meta information
  mainSections = ["blog"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2 January 2006" # Change the format of dates
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  customCSS = ["css/robinvenables.css"]
  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
  highlightColor = "#3eb489" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "img/logo.jpeg" # Logo image. Path relative to "static"
  subtitle = "Husband • Father • Dog Owner • Scuba Diver • IT Consultant" # Logo subtitle

[Params.thumbnail]
  visibility = ["list"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = false # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  cached = false # activate cache if true
  # Enable parts of social widget
  linkedin = "robin-venables"
  github = "robinvenables"

[pagination]
  pagerSize = 5
